version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
  DownloadBundle:
    - location: bundle.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: before.sh
      timeout: 300
      runas: root
  Install:
    - location: install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 6000
      runas: ubuntu


