# Generated by Django 2.2.4 on 2019-08-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='msg',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
