# Generated by Django 2.2.4 on 2019-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatReg', '0002_auto_20190830_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='text',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
